server:
  port: 9000
spring:
  application:
    name: auth-server
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/users_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: ${GOOGLE_CLIENT_NAME}
        provider:
          google:
            user-name-attribute: email
client-app:
  url: ${CLIENT_URL:http://localhost:8090}

auth-service:
  url: ${AUTH_SERVER:http://localhost:9000}